requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "logreg-sim-ic"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.15.2",
#    "flwr-datasets[vision]>=0.5.0",
    "scikit-learn==1.4.2",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "erick"

[tool.flwr.app.components]
serverapp = "logreg_sim_ic.server_app:app"
clientapp = "logreg_sim_ic.client_app:app"
[tool.flwr.app.config]
num-server-rounds = 5
penalty = "l2"
local-epochs = 1

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 3
